name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels: ['feature','enhancement']
  - title: 'ğŸ› Fixes'
    labels: ['bug','fix']
  - title: 'ğŸ§° Maintenance'
    labels: ['chore','ci','docs']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changes
  $CHANGES
